# NestJS Class Diagram - AppModule

direction: down

classes: {
  container-expanded: {
    shape: rectangle
    style.border-radius: 32
    style.stroke-dash: 3
    label.near: bottom-left
    style.stroke: "#666666"
    style.font-color: "#333333"
  }
}

AppModule: AppModule {
  class: [container-expanded]

}
